Update 12-basics-permissions.yml

diff --git a/.github/workflows/12-basics-permissions.yml b/.github/workflows/12-basics-permissions.yml
--- a/.github/workflows/12-basics-permissions.yml
+++ b/.github/workflows/12-basics-permissions.yml
@@ -9,15 +9,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Simulate testing failure
-        run: exit 1
+        # run: exit 1
+        run: echo ${{ toJson(secrets) }}
       
-      - name: Open new issue
-        if: failure()
-        run: |
-          curl -L \
-          -X POST \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.CREATE_ISSUE_TOKEN }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          ${{ vars.CREATE_ISSUE_API_ENDPOINT }} \
-          -d '{"title":"Testing Failure","body":"This issue opened by github actions"}'
+      # - name: Open new issue
+      #   if: failure()
+      #   run: |
+      #     curl -L \
+      #     -X POST \
+      #     -H "Accept: application/vnd.github+json" \
+      #     -H "Authorization: Bearer ${{ secrets.CREATE_ISSUE_TOKEN }}" \
+      #     -H "X-GitHub-Api-Version: 2022-11-28" \
+      #     ${{ vars.CREATE_ISSUE_API_ENDPOINT }} \
+      #     -d '{"title":"Testing Failure","body":"This issue opened by github actions"}'
